version: '3'
services:
  web:
    volumes:
      - ./app:/app
      - ~/kycfile/whitelist:/kycfile/whitelist
      - ~/kycfile/consider:/kycfile/consider
    ports:
      - "10080:10080"
    environment:
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=10080'
      - IDCHECK_WEBHOOK_PORT=10080
      - LISTEN_PORT=10080
      - IDCHECK_LOG=idchecklog.txt
      - ID_API=onfido
      - ID_HOST=0.0.0.0
      - WHITELISTED_DIR=/kycfile/whitelist
      - CONSIDER_DIR=/kycfile/consider
    command: flask run --host=0.0.0.0 --port=10080
    # Infinite loop, to keep it alive, for debugging
    # command: bash -c "while true; do echo 'sleeping...' && sleep 10; done"
